# Uncomment the next line to define a global platform for your project
source 'https://cdn.cocoapods.org/'
platform :ios, '14.0'
use_frameworks!
inhibit_all_warnings!

def shared_pods
  
  # Networking
    pod 'Alamofire'
    pod 'Starscream'
  
    # UI
    pod 'SDWebImage'
    pod 'SDWebImageSVGCoder'
    pod 'InfiniteLayout'
    pod 'IQKeyboardManagerSwift'
    pod 'SnapKit'
    pod 'SwiftEntryKit'
    pod 'YubiKit'
    pod "RecaptchaEnterprise"
    pod 'Firebase'
    pod 'FirebaseMessaging'
    pod 'SimpleQRCode'
	
    #SwiftLint
    pod 'SwiftLint'

	

end
  
target 'Probit' do
  shared_pods

  target 'ProbitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProbitUITests' do
    # Pods for testing
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        end
    end
end
